site_name: IA-COM-Controller
repo_url: https://x-access-token:${PERSONAL_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
site_author: Claus Zielke
nav:
    - Home: index.md
    - Setup: setup.md
    - Configuration: configuration.md
    - Application: 
      - Application: application.md
      - Sources: sources.md
      - Outputs: outputs.md
    - Todo: todo.md
theme: material